In [2]:
import torch
import numpy as np
np.set_printoptions(precision=3)

In [3]:
a = [1,2,3]
b = np.array([4,5,6], dtype=np.int32)

In [4]:
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

In [5]:
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [8]:
t_ones = torch.ones(2,3)
t_ones.shape

torch.Size([2, 3])

In [9]:
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
t_rand = torch.rand(2,3)
print(t_rand)

tensor([[0.7335, 0.8399, 0.8170],
        [0.2361, 0.4357, 0.3898]])


In [13]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


In [15]:
t = torch.rand(3,5)
t_tr = torch.transpose(t,0,1)
print(t.shape, ' -- to --> ', t_tr.shape)

torch.Size([3, 5])  -- to -->  torch.Size([5, 3])


In [16]:
t = torch.zeros(30)
t_reshape = t.reshape(5,6)
print(t.shape, ' -- to --> ', t_reshape.shape)

torch.Size([30])  -- to -->  torch.Size([5, 6])


In [18]:
t = torch.zeros(1,2,1,4,1)
t_sqz = torch.squeeze(t,2)
print(t.shape, ' -- to --> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])  -- to -->  torch.Size([1, 2, 4, 1])
